Controllers/OwnerMembershipSignupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageThree.Data;
using GarageThree.Models.ViewModels;
using GarageThree.Models;

namespace GarageThree.Controllers
{
    public class OwnerMembershipSignupsController : Controller
    {
        private readonly GarageContext _context;

        public OwnerMembershipSignupsController(GarageContext context)
        {
            _context = context;
        }

        // GET: OwnerMembershipSignups/Create
        public IActionResult Signup()
        {
            return View();
        }

        // POST: OwnerMembershipSignups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Signup([Bind("Id,FirstName,LastName,Age,PhoneNumber,PersonalNumber,Password,Email")] OwnerMembershipSignup ownerMembershipSignup)
        {

            if (ModelState.IsValid)
            {
                var owner = new Owner
                {
                    Age = ownerMembershipSignup.Age,
                    FirstName = ownerMembershipSignup.FirstName,
                    LastName = ownerMembershipSignup.LastName,
                    //FullName = $"{ownerMembershipSignup.FirstName + " " + ownerMembershipSignup.LastName}"
                    Phone = ownerMembershipSignup.PhoneNumber,
                    Membership = new Membership
                    {
                        PhoneNumber = ownerMembershipSignup.PhoneNumber,
                        Password = ownerMembershipSignup.Password,
                        PersonalNumber = ownerMembershipSignup.PersonalNumber,
                        Email = ownerMembershipSignup.Email,
                        RegistrationTime = DateTime.Now
                    }
                };

                //Todo If ownerMembershipSignup.Age redirect to index .... Else redirect to create vehicle

                _context.Add(owner);
                await _context.SaveChangesAsync();
                if (ownerMembershipSignup.Age >= 18)
                {
                    TempData["OwnerID"] = owner.Id;
                    return RedirectToAction("Park", "Park");
                }
                    
                //RedirectToAction("actionName", "controllerName"
                return RedirectToAction("Index","Park");

            }
            return View(ownerMembershipSignup);
        }

    }
}

Controllers/ParkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageThree.Data;
using GarageThree.Models;
using GarageThree.ViewModels;

namespace GarageThree.Controllers
{
    public class ParkController : Controller
    {
        private readonly GarageContext _context;

        public ParkController(GarageContext context)
        {
            _context = context;
        }

        // GET: Park
        public async Task<IActionResult> Index()
        {
            var garageContext = _context.Vehicles.Include(v => v.VehicleType);
            return View(await garageContext.ToListAsync());
        }

        public async Task<IActionResult> ParkinSpots()
        {
            var garageContext = _context.ParkingSpots.Include(p => p.Vehicles).OrderBy(p => p.ParkingId);
            return View(await garageContext.ToListAsync());
        }

        public async Task<IActionResult> Collect()
        {
            var garageContext = _context.Vehicles.Include(v => v.VehicleType).Include(ps => ps.ParkingSpot);
            return View(nameof(Collect), await garageContext.ToListAsync());
        }

        public async Task<IActionResult> FilterCollect(string RegistrationNumber = null)
        {
            if (!String.IsNullOrWhiteSpace(RegistrationNumber))
            { 
                var model = _context.Vehicles.Include(v => v.VehicleType)
                .Include(ps => ps.ParkingSpot)
                .Where(v=>v.RegistrationNumber.Contains(RegistrationNumber));
        
                return View(nameof(Collect), await model.ToListAsync());
            }

            TempData["Empty"] = "Registration number could not be found";

            return RedirectToAction(nameof(Collect));
        }

        // GET: Park/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var vehicle = await _context.Vehicles
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // GET: Park/Create
        public IActionResult Park()
        {
            ViewData["VehicleTypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id");
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id"); // Add with ViewData to Allow for Create Vehicle.
            return View();
        }

        // POST: Park/Park
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Park([Bind("Id,OwnerId,RegistrationNumber,Passengers,Color,Wheels,VehicleTypeId")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                
                var ownerId = _context.Owners.Where(o => o.Id == vehicle.OwnerId);
                if (!ownerId.Any())
                {
                    // TODO SWAP TO DEPENDECY INJECTION-
                    ModelState.AddModelError("OwnerId", "New to the Garage? Sign up here");
                    return View(vehicle);
                }
                if (_context.Vehicles.Where(v=>v.RegistrationNumber.Contains(vehicle.RegistrationNumber)).Count()>0) // Select(v=>v).ToList().
                {
                    // TODO SWAP TO DEPENDECY INJECTION-
                    ModelState.AddModelError("RegistrationNumber", "Registration number must be unique");
                    return View(vehicle);
                }
                var ageVehicleAbove18 = _context.Owners
                    .Include(o => o.Vehicles.Where(v => v.Id == vehicle.Id)) // Query Vehicle
                    .FirstOrDefault().Age >= 18; //Query Owner

                if (!ageVehicleAbove18) 
                {
                    ModelState.AddModelError("Age", "You are too young to park that Vehicle here, Find an older member to help you");
                    return View(vehicle);
                }

                vehicle.ArrivalTime = DateTime.Now;
                _context.Vehicles.Add(vehicle);

                var availibleParks = _context.ParkingSpots.Include(ps => ps.VehicleParkingSpots).FirstOrDefault(); // NR0 returned.
                var availibleParks2 = _context.ParkingSpots.Include(ps => ps.VehicleParkingSpots).Where(ps => ps.Id == 2).FirstOrDefault(); // Works 2nd returned
                var availibleParks3 = _context.ParkingSpots.Include(ps => ps.VehicleParkingSpots.Where(vps=> vps.Vehicle == null)).FirstOrDefault(); // Works
                var availibleParks4 = _context.ParkingSpots
                    .Include(ps => ps.VehicleParkingSpots)
                    .Where(ps => ps.VehicleParkingSpots.Count == 0)
                    .FirstOrDefault(); 
                var allParkings = _context.ParkingSpots.Include(ps => ps.VehicleParkingSpots).ToList();

                var newParking = new VehicleParkingSpot
                {
                    ParkingSpot = availibleParks4,
                    Vehicle = vehicle
                };

                _context.Add(newParking);
                              
                TempData["Success"] = $"Vehicle {vehicle.RegistrationNumber} succesfully parked at Parking: {vehicle.ParkingSpot.FirstOrDefault().ParkingId}";
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // TODO SWAP TO DEPENDECY INJECTION-
            ViewData["VehicleTypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id", vehicle.VehicleTypeId);
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id", vehicle.OwnerId); // Id Value, Text
            return View(vehicle);
        }


        public async Task<IActionResult> ParkExisting(int? Id)  //Asp item Vehicle.OwnerID
        {
            var vehicles = _context.Vehicles.Where(v=> v.Id == Id); // Get Vehicles
            var vehicle = vehicles.FirstOrDefault(); // First Vehicle
            vehicle.ArrivalTime = DateTime.Now;
            var availibleParks4 = _context.ParkingSpots
                .Include(ps => ps.VehicleParkingSpots)
                .Where(ps => ps.VehicleParkingSpots.Count == 0)
                .FirstOrDefault();

            var newParking = new VehicleParkingSpot
            {
                ParkingSpot = availibleParks4,
                Vehicle = vehicle
            };
            _context.Add(newParking);
            await _context.SaveChangesAsync();

            return RedirectToAction("Overview","Park");
        }

        // GET: Park/Edit/5
        public async Task<IActionResult> Edit(int? id) // DbContext Method?
        {
            if (id == null)
            {
                return NotFound();
            }
            var vehicle = await _context.Vehicles.FindAsync(id);

            if (vehicle == null)
            {
                return NotFound();
            }
            //ViewData["VehicleTypeId"] = new SelectList(_context.VehicleTypes, "Id", "Id", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        public async Task<IActionResult> OverView() //2.0 => 3.0
        {
                var model = _context.Vehicles.Select(v => new VehiclesOverView
                {
                    Id = v.Id,
                    Regnum = v.RegistrationNumber,
                    Model = v.Model,
                    Arrivaldate = v.ArrivalTime,
                    ParkedTime = (DateTime.Now - v.ArrivalTime),
                    //3.0
                    OwnerID = v.OwnerId,
                    MembershipId = _context.Memberships.FirstOrDefault(m => m.Id == v.OwnerId).Id, // Bara Membership ID
                    Membership = _context.Memberships.FirstOrDefault(m => m.Id == v.OwnerId), // Hela membership
                    VehicleType = v.VehicleType,
                    ParkingSpots = v.ParkingSpot
                });

            return View("OverView", await model.ToListAsync());
        }

        public async Task<IActionResult> FilterOverView(int OwnerID)
        {
            var vehicles = _context.Vehicles.Where(v => v.OwnerId == OwnerID);
            var model = vehicles.Select(v => new VehiclesOverView
            {
                Id = v.Id,
                Regnum = v.RegistrationNumber,
                Model = v.Model,
                Arrivaldate = v.ArrivalTime,
                ParkedTime = (DateTime.Now - v.ArrivalTime),
                OwnerID = v.OwnerId,
                MembershipId = _context.Memberships.FirstOrDefault(m => m.Id == v.OwnerId).Id, // Bara Membership ID
                Membership = _context.Memberships.FirstOrDefault(m => m.Id == v.OwnerId), // Hela membership
                VehicleType = v.VehicleType,
                ParkingSpots = v.ParkingSpot
            }).ToListAsync(); // ToListAstync()

            return View("OverView", await model); // Await model.ToListAsync()
        }

        public async Task<IActionResult> MembersOverview() // Automapper.... OM JAG FÅR ETT ID så...
        {
            var model = _context.Memberships.Select(m => new MembersOverview
            {
                Id = m.Id,
                OwnerId = m.OwnerId, //  Todo Unique property
                Email = m.Email,
                Vehicles = _context.Vehicles.Where(v=> v.OwnerId == m.OwnerId).ToList(), // Med Hidden ID i nästa steg. DETAILS
                VehicleCount = _context.Vehicles.Where(v => v.OwnerId == m.OwnerId).Count()
            });
            return View(await model.ToListAsync());
        }

        [HttpGet]

Controllers/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GarageThree.Data;
using GarageThree.Models;
using GarageThree.ViewModels;

namespace GarageThree.Controllers
{
    public class VehicleTypesController : Controller
    {
        private readonly GarageContext _context;

        public VehicleTypesController(GarageContext context)
        {
            _context = context;
        }

        // GET: VehicleTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.VehicleTypes.ToListAsync());
        }

        // GET: VehicleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleTypCreateViewModel vehicleTypCreateViewModel)
        {
            if (ModelState.IsValid)
            {
                var vehicleType = new VehicleType
                {
                    Price = vehicleTypCreateViewModel.Price,
                    Size = vehicleTypCreateViewModel.Size,
                    TypeName = vehicleTypCreateViewModel.TypeName,
                    ReqparkingSpots = vehicleTypCreateViewModel.ReqparkingSpots
                };
                _context.Add(vehicleType);
                TempData["Success"] = $"Vehicle Type {vehicleType.TypeName} Succesfully Added to Database.";
                await _context.SaveChangesAsync();
                
                return RedirectToAction("Park", "Park");
            }
            return View(vehicleTypCreateViewModel);
        }

        // GET: VehicleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes.FindAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Size,TypeName,ReqparkingSpots,Price")] VehicleType vehicleType)
        {
            if (id != vehicleType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleTypeExists(vehicleType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicleType = await _context.VehicleTypes.FindAsync(id);
            _context.VehicleTypes.Remove(vehicleType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleTypeExists(int id)
        {
            return _context.VehicleTypes.Any(e => e.Id == id);
        }
    }
}

Views/Park/Collect.cshtml
@model IEnumerable<GarageThree.Models.Vehicle>

@{
    ViewData["Title"] = "Collect";
}

<h1>Collect Vehicle</h1>


@if (TempData["Empty"] != null)
{
<p class="text-danger">@TempData["Empty"].ToString()</p>

}


<form asp-action="FilterCollect" method="get">
    <div class="input-group mb-3">
        <input type="text" name="RegistrationNumber" class="form-control" placeholder="Search on Registration Number...">
        <div class="input-group-append">
            @*<select name="vehicleType" asp-items="@Html.GetEnumSelectList<VehicleTypes>()" class="form-control">
                    <option selected="selected" value="">All Types of Vehicles</option>
                </select>*@
        </div>
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary btn-outline-secondary" id="search-btn"><i class="fa fa-search">&emsp;Search</i></button>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Passengers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wheels)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType)
            </th>
            <th>
                @*Html.DisplayNameFor(model => model.ParkingSpots)*@
                Parking Spot
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Passengers)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wheels)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleType.Id)
                </td>
                <td>
                    @foreach (var spot in item.ParkingSpot)
                    {
                       <span> @spot.ParkingId</span>
                    }
                </td>
                <td>

                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Receipt" asp-route-id="@item.Id">Collect and Receipt(delete cascade)</a>|
                    <a asp-action="Unpark" asp-route-id="@item.Id">UNPARK vehicle</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Park/Details.cshtml
@model GarageThree.Models.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Passengers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passengers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Park/Edit.cshtml
@model GarageThree.Models.Vehicle
@inject IGetVehicleTypesService service
@inject IDevelopmentGetOwnerService developmentService

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<input type="hidden" asp-for="ArrivalTime" /> DO NOT DO THIS ! *@
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items=@await developmentService.DevelopmentGetOwners()></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Passengers" class="control-label"></label>
                <input asp-for="Passengers" class="form-control" />
                <span asp-validation-for="Passengers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wheels" class="control-label"></label>
                <input asp-for="Wheels" class="form-control" />
                <span asp-validation-for="Wheels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select asp-for="VehicleTypeId" class="form-control" asp-items=@await service.GetVehicleTypesAsync()></select>
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Park/MemberDetails.cshtml
@model IEnumerable<GarageThree.ViewModels.OwnerVehicleView>

@{
    ViewData["Title"] = "MemberDetails";
}

<h1>MemberDetails</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles)

            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @foreach (var vehicle in item.Vehicles)
                {
                    <span>Regnum: @vehicle.RegistrationNumber Color: @vehicle.Color </span><br>
                }
            </td>




        </tr>
}
    </tbody>
</table>

Views/Park/Park.cshtml
@model GarageThree.Models.Vehicle
@inject IGetVehicleTypesService service
@inject IDevelopmentGetOwnerService developmentService

@{
    ViewData["Title"] = "Park";
}




<h1 class="row d-flex justify-content-center">Park Your Vehicle <i class="fa fa-car fa-2x ml-2"></i></h1>


<hr />

@if (TempData["Success"] != null)
{
    <div class="index-options text-center text-success" id="threeSeconds">
        <H1>@TempData["Success"].ToString()</H1>
    </div>
}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 md-1">
            <form asp-action="Park">
                <div class="row">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group col-md-12 mb-3">
                        <label asp-for="OwnerId" class="control-label"><b>Your Owner ID</b></label>
                        @if (TempData["OwnerID"] != null)
                        {
                            <div class="index-options text-center text-success">
                                <p>Your ownder id is: @TempData["OwnerID"].ToString()</p>
                            </div>
                        }
                        <input asp-for="OwnerId" class="form-control" value="@TempData["OwnerID"]" />
                        <span asp-validation-for="OwnerId" class="text-danger"></span>
                        <div>
                            <span>
                                If you are not a Member <a class="nav-link" asp-area="" asp-controller="OwnerMembershipSignups" asp-action="Signup">Signup Here</a>
                            </span>
                        </div>
                    </div>

                    <br />
                    <div class="form-group col-md-6 mb-3">
                        <div>@*TODO*@---<b>REGISTER A NEW VEHICLE</b>----</div>
                        <label asp-for="RegistrationNumber" class="control-label"></label>
                        <input asp-for="RegistrationNumber" class="form-control" />
                        <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6 mb-3">
                        <label asp-for="Passengers" class="control-label"></label>
                        <input asp-for="Passengers" class="form-control" value="1" min="1" />
                        <span asp-validation-for="Passengers" class="text-danger" value="4" min="1"></span>
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label asp-for="Color" class="control-label"></label>
                        <input asp-for="Color" class="form-control" value="RedGreen" />
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6 mb-3">
                        <label asp-for="Wheels" class="control-label"></label>
                        <input asp-for="Wheels" class="form-control" value="4" min="1" />
                        <span asp-validation-for="Wheels" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label asp-for="VehicleTypeId" class="control-label">Vehicle Type</label>
                        <select asp-for="VehicleTypeId" class="form-control" asp-items=@await service.GetVehicleTypesAsync();></select>
                    </div>
                </div>
                <div>@*TODO*@---<b>ADD A NEW TYPE OF VEHICLE</b>----</div>

                <div>
                    <span>
                        If you cannot find your mode of Transportation <a class="nav-link" asp-area="" asp-controller="VehicleTypes" asp-action="Create">Click Here to add it</a>
                    </span>
                </div>
                <div>
                    <p>Your Arrival Time: @DateTime.Now</p>
                </div>
                <div class="form-group">
                    <input type="submit" value="Park Vehicle" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div>
        <a asp-action="Index"><i>Back to Main Menu</i></a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Park/ParkinSpots.cshtml
@model IEnumerable<GarageThree.Models.ParkingSpot>



@{
    ViewData["Title"] = "ParkinSpots";
}

<h1>ParkinSpots</h1>

<p>
    <a asp-action="Park">Park new vehicle</a> 
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ParkingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vehicles)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ParkingId)
            </td>
            <td>
                 @foreach (var vehicle in item.Vehicles)
                 {
                     <span>@vehicle.RegistrationNumber</span>
                 }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>